"""add url unique

Revision ID: 00cdbcd1a30b
Revises: 2fe5cc4612f1
Create Date: 2022-11-03 02:42:10.108839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00cdbcd1a30b'
down_revision = '2fe5cc4612f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'url', ['reduction_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url', type_='unique')
    # ### end Alembic commands ###
